### PR TITLE
pagination on branch page

### LINKED ISSUE #34: Pagination on Branch Page
Updating the current state of pagination using existing react-pagination.

### PR DESCRIPTION
**Pull request by mdasifmunshe**
This change resolves #34 by a actual working pagination
Signed-off-by: Md Asif Munshe <asif35-2872@diu.edu.bd>

### CODE REVIEW

**Comment by mdasifmunshe** [comment]
As packages were not locked to a specific version as a result the yarn.lock/package-lock.json file was upgraded.

**Comment by harunurkst** [comment]
@tusheer please review this

**Comment by tusheer** [comment]
@mdasifmunshe Bhai, I appreciate your contribution. Here is some feedback for you.

- Since we will paginate based on the API call, there is no need to modify the local state by slicing. Instead, we can keep things as they are.
`
 const [currentPage, setCurrentPage] = useState(1);
    const contentsPerPage = 5;

    const handlePageClick = (data: { selected: number }) => {
        setCurrentPage(data.selected + 1);
    };
`
- The pagination design is flawed because the two buttons are not properly spaced. To fix this, the buttons should be justified with space between them
image

**Comment by mdasifmunshe** [comment]
@tusheer Thanks for the feedback.

**Pull request closed without merging**
