### PR TITLE
Member Detail API

### PR DESCRIPTION
**Pull request by rahidulislam**
1. unnecessary file without __init__.py is added in gitignore
2. member detail serializer is changed
3. saving and loan info in member detail is added. I am confused in this API (MemberSavingLoanInfo)

### CODE REVIEW

**Comment by harunurkst** [comment]
please resolve merge conflict

**Comment by rahidulislam** [comment]
i resolved this. migration file is not necessary to upload in github. it conflict each other.

**Comment by rabiulislam-xyz** [comment]
Migration files are necessary, you should add new migration files on top of existing migrations if you need them.

Deleting/updating existing files will cause issues for everyone else (including the servers) who already using the existing migrations.

**Comment by rahidulislam** [comment]
migration file is removed from .gitignore

**Comment by rabiulislam-xyz** [comment]
check the files changed list (33 files changed), as this PR is for member details API, only related files should be changed. you can make distinct PR for other changes.

**Pull request closed without merging**
