### PR TITLE
landing page width update and scroll bar styling done

### PR DESCRIPTION
**Pull request by mahfuzurrahman01**
Set the landing page width to fit all devices and add some style to the scroll bar as per the website design.

### CODE REVIEW

**Comment by osama2kabdullah** [comment]
Hello @mahfuzurrahman01 

I am new in Front-end Web development. After cloning this repository in my local machine, I want to contribute to this project's Front-end. When I start the development server, I face an error.
```
Error: Invalid environment variables
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```
In the terminal-
```bash
error - src/env.mjs (51:14) @ eval
error - Error: Invalid environment variables
    at eval (webpack-internal:///./src/env.mjs:53:15) {
  page: '/'
}
  49 |         // eslint-disable-next-line no-console
  50 |         console.error('❌ Invalid environment variables:', parsed.error.flatten().fieldErrors);
> 51 |         throw new Error('Invalid environment variables');
     |              ^
  52 |     }
  53 | 
  54 | 
```
__Why do I face this error and how to resolve this?__

**Comment by mahfuzurrahman01** [comment]
because there is no .env file in your project (Frontend)
I'll explain the steps:
1. after cloning and change directory to frontend folder and open with vs
code
2. run => npm install
3. look there is an .env.example file just copy the whole code inside this
file
4. create .env file in root and paste that copied code in .env file
5. then run npm run start

hope it will work. if not work then let me know

**Comment by osama2kabdullah** [comment]
Thanks, @mahfuzurrahman01 . It's working.
I thought the `.env.example` file was working.

**Comment by harunurkst** [comment]
@mahfuzurrahman01 you may update README.md file with this information

**Pull request merged**
