### PR TITLE
Create an API to create new Team #17

### PR DESCRIPTION
**Pull request by siyam04**

### CODE REVIEW

**Comment by harunurkst** [comment]
what this pull request doing?  
If I post request to this url: /api/v1/organization/teams/ 
with   
```
{
  "name": "বেলি",
  "owner": 2
}```
it shows the error  
```
IntegrityError at /api/v1/organization/teams/
NOT NULL constraint failed: organization_team.branch_id
```

**Comment by siyam04** [comment]
Ok I'll send another PR soon

**Comment by siyam04** [comment]
FIXED :: Create an API to create new Team #17 #42

Plz chk latest PR

**Comment by harunurkst** [comment]
brother, you should test before push, still your code raising error
```
django.db.utils.IntegrityError: NOT NULL constraint failed: organization_team.branch_id
```
```team = Team.objects.create(**validated_data)
   team.branch = validated_data['owner'].branch
```
If you use create() method then it will try to create Team object in DB, but still, the branch is empty. So, it should be, 
```
team = Tem(**validated_data)

**Pull request merged**
